# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-04"

[[extensions]]
name = "cod-thank-you-block"
handle = "cod-thank-you-block"
type = "ui_extension"
uid = "83906e22-38c1-0b0a-a07a-f20611508cc701a7baa2"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
api_access = true
network_access = true


# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

[[extensions.metafields]]
namespace = "$app"
key = "requestedFreeGift"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"